version: '3'

services:
  nginx:
    image: "smbrtprmnk/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'


  # postgres: 
  #   image: 'postgres:latest'
  #   environment:
  #     - POSTGRES_PASSWORD=postgres_password

  # redis:
  #   image: 'redis:latest'

  server:
    image: "smbrtprmnk/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT

  client:
    image: "smbrtprmnk/multi-client"
    mem_limit: 128m
    hostname: client

  worker:
    image: "smbrtprmnk/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT


